[package]
name = "getting-started-with-bevy"
version = "0.1.0"
authors = ["José Alex <jacoqueiro@rd.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", features = ["bevy_wgpu"] }